# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store
  end

  lane :hockeyapp do
    gradle(
  	  task: 'assemble',
  	  build_type: 'hockeyApp'
    )

    hockey(
      api_token: "452430e865d944509238cd84def2fe10",
  	  apk: "app/build/outputs/apk/app-release.apk",
  	  notes: "yay!",
  	  notify: "0"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
